### PR TITLE
Add travis support for CI

### PR DESCRIPTION
**Pull request by SergeStinckwich**
I add travis support for SSM in order to use continuous integration for the project.
The project is green at the moment, look here: https://travis-ci.org/SergeStinckwich/ssm
The build result is displayed on the README file.
You have to create your own travis account (this is free) in order to use CI.

### CODE REVIEW

**Comment by sballesteros** [comment]
Thanks and sorry for the super long delay to "merge" this. @JDureau told me recently that he was working back on SSM so things should move a bit in the near future.

**Comment by SergeStinckwich** [comment]
Thank you @sballesteros ! What is the future of SSM ?
I would like to integrate some aspects of SSM with our epidemiological DSL: https://github.com/UMMISCO/Kendrick
We are working currently on spatial and network extensions.

**Comment by JDureau** [comment]
We're going to work on solidifying the current code basis and widen the tests coverage.
We won't be integrating spatial structure in SSM, the idea is that it serves as a basis for higher-level modelling layers. Like Kendrick, for example.

**Comment by SergeStinckwich** [comment]
Great @JDureau !
Yes I agree with you, SSM should be used as a core for a more high level modelling platform.
We are implementing various epidemiology concerns in Kendrick with a high-level DSL (hosts heterogeneity, network, spatial, mobility, ...) and after that generate the set of ODEs, that could be explored with SSM I guess latter.

**Pull request closed without merging**
